### ISSUE TITLE
Means of supporting patches/game mods

### ISSUE THREAD

**Issue by Casuallynoted** [Team-Resurgent/Repackinator#33]
Hello!

This is probably a stretch goal kind of idea, but it would be awesome to see the ability to apply some types of patches to the CCI output. Specifically thinking like patches to force 480p, 128mb ram patches, and patches to offload DLC/TUs to the F and G drives might be really useful!

**Comment by Natetronn** [comment]
It's my understanding that's why CCI was made to begin with, at least in part (with many more cool features too), versus using plain ol' CSO, so such things could be included when it made sense to do so. I'm not sure on the specifics of any of those particular features, per se, but nice knowing it may be a possibility. Although, having said that, it may be more of a Cerbios specific thing and CCI just supports it. Either way, excited to see what's to come.
