### ISSUE TITLE
Not actually repacking?

### ISSUE THREAD

**Issue by heymufti** [Team-Resurgent/Repackinator#54]
Why is this called "repackinator" when it's clearly not repacking anything?  The end result xiso is many times larger than extracting files and actually repacking.  There are only a few titles that check the size of the DVD partitions.  Can we get an option to actually repack the iso's appropriately?  It looks like the smallest xiso your tool creates is 1,756,807,168 bytes x2 split.  Is this just removing a video partition and not data padding?

extract-xiso does this; https://github.com/XboxDev/extract-xiso

You can use;

extract-xiso -x ./redump_disc.iso
extract-xiso -c ./redump_disc_folder

And run the attach script from xbmc4gamers.  So why can't this functionality be apart of Repackinator?

**Comment by incursion64** [comment]
Well, there is quite a bit to "unpack" here.  Let me try to explain to you what's going on in simple terms that helped me understand the process here.  

Extract XISO is removing the padding and extracting the content into a foldered state.  When you use the -r command it removes the padding and rebuilds the XISO so the size is smaller than what you started it. 

Repackinator requires the user to select some options. You have Trim/Scrub, and you have Compression (CCI).  
Without checking any of these boxes it's simply removing the video partition and it's splitting the 6.7GB disc into two halves as and XISO.  This is essentially a full size game rip without any patching, no sector changes etc. It's 1:1 that can be used on the xbox.  Repackinator will also folderize this file and create your attach XBE so there is no need for running a script. It extracts the information from XBE, matches up to the JSON file, and that's what you end up with.

Now -when you select Trim-Scrub - It is replacing all that padding with 0's instead of removing the padding. This keep the actual data in the same location as it were on a full size disc, yet the file size is slightly smaller than the original 1:1 rip. 

Now for the compression CCI or CSO, it compresses all the data and all those 0's that maintain sector integrity can squished down to basically nothing.  The result are files that are basically the same size of and HDD extracted folder with zero patching, and with nothing moved.  This basically gives you max compatibility.  

Hope that makes sense.
