### ISSUE TITLE
Option to keep original file name rather than using the name in the JSON

### ISSUE THREAD

**Issue by RibShark** [Team-Resurgent/Repackinator#59]
I would like the option to keep the current filename when repacking (and also use that name in default.xbe/default.tbn). I use redump.org dumps and I prefer the region naming scheme there, being tied to which regions the game actually released in rather than what the XBE is flagged as which allows for better organisation of multiple releases.

**Comment by incursion64** [comment]
You can custom edit any name in the app but clicking on the title.  You can also edit/make your own json file to name however you would like. Naming has to be compliant with character limits etc, there are too many variables with naming. Personally I don't like (GLO, USA etc.) in my file names so i just edited my json in excel.  As far as the region, it's set to whatever is in the games XBE, not sure why you would want it otherwise as you can run into compatibility issues.  Editing your JSON (carefully) is the way to go for those who want things very specific. You can also pull from the atl list too.  It's a lot of work mind you, but it's the type of work you likely only have to do once.
