### ISSUE TITLE
Games not found in either .json. Add ability to just process all iso and ignore the json.

### ISSUE THREAD

**Issue by dystopia2017** [Team-Resurgent/Repackinator#70]
Sometimes iso's are not found in either json file, like rev1 and rev2 isos of games.
Is there anyway to just process all isos and ignore the json files? it's quite annoying
when it skips games with the error not found. when the iso is good and matches redump set.

![annoying](https://github.com/Team-Resurgent/Repackinator/assets/30868809/9fc938b3-fa3e-467b-b319-e36c43530a14)

**Comment by frehov** [comment]
Not without a bit of fiddling.

You need to extract the default.xbe from the iso, then out the necessary info and checksums of the ISOs you want to process into a json file.

Closing this issue as this probably won't be planned or worked on any further.

The curated list exists, because otherwise people would blame repackinator for what could be bad rips or any other multitude of things that are not repackinators fault.
